### ISSUE TITLE
Control the camera zoom

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [BugsForDays/libsonyapi#2]
I am building a GUI application for my camera (sonyHx400v) using this library. The problem that I face is that I am not able to control the zoom to a particular value, even though I am able to zoom in and zoom out using 1shot.

**Comment by petabite** [comment]
Hi,

From looking at the documentation, it doesn't seem that it is possible to zoom to a particular value.

However, a possible solution could be to combine `actZoom` and Event notification (`getEvent`) to create a feedback loop of sorts.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/24444266/128112378-4e8b6c4f-9430-4fe2-806f-a3d449f21870.png">

**pg. 54**

You could use the `zoomPosition` value that is returned to figure out how far you are zoomed in. Then keep calling `actZoom` with the `1shot` movement parameter and read `zoomPosition` again until you reach your desired zoom percentage.

Hope that helps.

**Comment by SureshbabuAkash1999** [comment]
Thank you so much for your support.
