### ISSUE TITLE
connect to known camera IP

### ISSUE THREAD

**Issue by inspire22** [BugsForDays/libsonyapi#3]
Thanks for this project!

I'm trying to connect to an older sony RX100 III to do some automated 3d scanning.

My router & many routers seem to hate UPNP these days, and I'm struggling to get them connected.  I can see in my router the camera and my computer are both connected & know it's IP - is there any way to hack past the discovery() method and connect directly to the camera?  I tried looking through the code but I don't know what the xml_address is supposed to look like...

Thanks!

**Comment by petabite** [comment]
Hi Kevin,

Thanks for reaching out! I saw that you mentioned a router involved. Your computer actually needs to be connected directly to your camera's wifi network in order for the Sony Camera Remote API to work. Here's a support article that might help: [DSC-RX100M3: Remote shooting](https://support.d-imaging.sony.co.jp/www/cscs/pmm/page2.php?area=gb&lang=en&mdl=DSC-RX100M3&abil=31100&mode=connect). You can skip the steps involving launching Imaging Edge Mobile on your smartphone. Let me know if that helps!

**Comment by inspire22** [comment]
Brilliant!  I hadn't figured out how to run the app from the camera, I figured it was just run on the phone and they should both be on the same wifi access point, that makes way more sense now :)  Thanks so much for letting me know!

**Comment by petabite** [comment]
Glad I could help!
